metadata:
  name: athene-manager
  namespace: monitoring
  labels:
    app.kubernetes.io/name: athene-manager
spec:
  ports:
  - name: internal
    port: 9443
  - name: api
    port: 9444
  selector:
    app.kubernetes.io/name: athene-manager
kind: Service
apiVersion: v1
---
metadata:
  name: athene-manager
  namespace: monitoring
  labels:
    app.kubernetes.io/name: athene-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: athene-manager
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: athene-manager
    spec:
      serviceAccountName: athene-manager
      containers:
      - command:
        - /manager
        image: k3d-k3s-default-registry:41475/controller:latest
        name: athene-manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
kind: Deployment
apiVersion: apps/v1
---
metadata:
  name: athene-manager
  namespace: monitoring
kind: ServiceAccount
apiVersion: v1
---
metadata:
  name: athene-manager
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: athene-manager
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: athene-manager
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
