name: Go
on:
  pull_request:
  push:
    branches:
      - 'release-*'
      - 'main'
    tags:
      - 'v*'
env:
  golang-version: '1.16'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  node:
    name: Node
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: make install
      - run: make ui
      - name: Upload UI for Go API
        uses: actions/upload-artifact@v2
        with:
          name: ui
          path: cmd/api/ui
  go:
    needs:
      - node
    runs-on: ubuntu-latest
    name: Go
    steps:
      - name: Download UI for Go API
        uses: actions/download-artifact@v2
        with:
          name: ui
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.golang-version }}
      - run: make test
      - run: make api kubernetes filesystem

  container:
    name: Container
    needs:
      - node
      - go
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
