name: Go
on:
  pull_request:
  push:
    branches:
      - 'release-*'
      - 'main'
    tags:
      - 'v*'
env:
  golang-version: '1.16'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  go:
    needs:
      - node
    runs-on: ubuntu-latest
    name: Go
    steps:
      - name: Download UI for Go API
        uses: actions/download-artifact@v2
        with:
          name: ui
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.golang-version }}
      - run: make test
      - run: make api kubernetes filesystem
